export enum Roles {
    USER = "ROLE_USER",
    ADMIN = "ROLE_ADMIN",
    ENCARGADO_DE_JUGADORES = "ROLE_ENCARGADO_DE_JUGADORES",
    ENCARGADO_DE_TORNEOS = "ROLE_ENCARGADO_DE_TORNEOS",
    ENCARGADO_DE_SANCIONES = "ROLE_ENCARGADO_DE_SANCIONES"

}

